server:
  port: 8080

spring:
  application:
    name: airlines-study-case

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/airlines_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/api
airlines:
  security:
    jwt:
      secret: mySecretKeyForJWT12345678901234567890123456789012
      expiration: 86400000 # 24 saat

logging:
  level:
    com.airlines: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
